from .SimpleWindow import Initialize
from .SimpleWindow import Close
from .SimpleWindow import SetSize
from .SimpleWindow import GetSize
from .SimpleWindow import SetPosition
from .SimpleWindow import GetPosition
from .SimpleWindow import SetTitleBarColor
from .SimpleWindow import GetTitleBarColor
from .SimpleWindow import SetResizable
from .SimpleWindow import GetResizable
from .SimpleWindow import SetTopMost
from .SimpleWindow import GetTopMost
from .SimpleWindow import SetForeground
from .SimpleWindow import GetForeground
from .SimpleWindow import SetMinimized
from .SimpleWindow import GetMinimized
from .SimpleWindow import SetUndestroyable
from .SimpleWindow import GetUndestroyable
from .SimpleWindow import SetIcon
from .SimpleWindow import GetIcon
from .SimpleWindow import SetOpen
from .SimpleWindow import GetOpen
from .SimpleWindow import GetHandle
from .SimpleWindow import Show